-- TRUNCATE locations RESTART IDENTITY CASCADE;

DROP TABLE FEEDBACK;
DROP TABLE RECOMMENDATIONS;
DROP TABLE ACCOUNTS;
DROP TABLE AGENCY;
-- DROP TABLE LOCATIONS;
DROP TABLE ROLES;

CREATE TABLE ACCOUNTS ( 
	ACCOUNTID SERIAL PRIMARY KEY,
	ACCOUNTNAME CHARACTER VARYING(50) NOT NULL UNIQUE,
	PASSWORD CHARACTER VARYING(255) NOT NULL,
	FULLNAME CHARACTER VARYING(50) NOT NULL,
	DATEOFBIRTH TIMESTAMP,
	AVATAR TEXT, 
	POSITION CHARACTER VARYING(255), 
	CANDIDATEPLACE CHARACTER VARYING(255),
	STATUS CHARACTER VARYING(50),
	DATE_CREATED TIMESTAMP,
	UPDATED_DATE TIMESTAMP,
	AGENCYID SERIAL NOT NULL,
	ROLEID  SERIAL NOT NULL
);

CREATE TABLE AGENCY (
	AGENCYID SERIAL PRIMARY KEY,
	AGENCYNAME CHARACTER VARYING(255) NOT NULL UNIQUE,
	NOTE TEXT, STATUS CHARACTER VARYING(50),
	DATE_CREATED TIMESTAMP,
	UPDATED_DATE TIMESTAMP
);


CREATE TABLE FEEDBACK (
	FEEDBACKID SERIAL PRIMARY KEY,
	TITLE CHARACTER VARYING(50) NOT NULL UNIQUE,
	CONTENTS CHARACTER VARYING(50) NOT NULL,
	FILES CHARACTER VARYING(50) NOT NULL,
	DATE_CREATED TIMESTAMP,
	UPDATED_DATE TIMESTAMP,
	ACCOUNTID SERIAL NOT NULL,
	RECOMMENDATIONSID SERIAL NOT NULL
);

CREATE TABLE LOCATIONS (
	LOCATIONSID SERIAL PRIMARY KEY,
	NAME CHARACTER VARYING(255),
	PARENTID SERIAL,
	DATE_CREATED TIMESTAMP,
	UPDATED_DATE TIMESTAMP
);


CREATE TABLE RECOMMENDATIONS (
	RECOMMENDATIONSID SERIAL PRIMARY KEY,
	OBJECT SERIAL NOT NULL,
	FULLNAME CHARACTER VARYING(50),
	ADDRESS CHARACTER VARYING(255),
	PHONENUMBER CHARACTER VARYING(50),
	EMAIL CHARACTER VARYING(50),
	TITLE CHARACTER VARYING(50),
	CONTENTS TEXT, 
	FILES TEXT, 
	STATUS CHARACTER VARYING(50),
	FIELDS CHARACTER VARYING(255),
	REPORTINGDEADLINE SERIAL, 
	COMMENTTYPE CHARACTER VARYING(50),
	DATE_CREATED TIMESTAMP,
	UPDATED_DATE TIMESTAMP,
	AGENCYID SERIAL NOT NULL
);

CREATE TABLE ROLES (
	ROLEID SERIAL PRIMARY KEY,
	ROLENAME CHARACTER VARYING(50) NOT NULL UNIQUE,
	KEYNAME CHARACTER VARYING(50) NOT NULL UNIQUE
);

INSERT INTO roles(rolename, keyname) VALUES
('Quản trị viên1','ADMIN1'),
('Người dùng1','USER1')

